---
output: html_document
---

vuzunangelov & chrisw 20210210

# A Basic Toy Example For Running AKLIMATE On A Binary Classification Task

This is an example of how to run AKLIMATE on a binary classification task. Using this example, you can check if your installation of the AKLIMATE package is working. It also gives an example of how to set up an AKLIMATE experiment. Visit [the AKLIMATE github repo](https://github.com/VladoUzunangelov/aklimate) for more description of AKLIMATE parameters and options. A detailed description of AKLIMATE is presented in:

1- V. Uzunangelov, C. K. Wong, and J. Stuart. Highly Accurate Cancer Phenotype Prediction with AKLIMATE, a Stacked Kernel Learner Integrating Multimodal Genomic Data and Pathway Knowledge. [bioRxiv](https://www.biorxiv.org/content/10.1101/2020.07.15.205575v1), July 2020.

## Load AKLIMATE Library

Load the `aklimate` library.

```
library(aklimate)
```

## Loading Data

1- Load an object from file, "binary_classification_example_data.rdata".

2- The following data is available in `binary_classification_example_data`:

  + `pathways` is where AKLIMATE will look for feature sets. These are named lists of features.
  + `labels` is where the samples' true labels are found.
  + `sample_data` is where AKLIMATE will look for values of each sample's local features. For simplicity, this example does not use any global features.
  + `train_test_split` specifies which samples will be used for training and which will be used for testing.

```
load("binary_classification_example_data.rdata")

pathways <- binary_classification_example_data$pathways
labels <- binary_classification_example_data$labels
sample_data <- binary_classification_example_data$sample_data
train_test_split <- binary_classification_example_data$train_test_split
```

## Train an AKLIMATE Model

Train an AKLIMATE model using a call to `aklimate()`. In this example, the trained model is stored in the `aklimate_model` variable. Visit [the AKLIMATE github repo](https://github.com/VladoUzunangelov/aklimate) for descriptions of AKLIMATE parameters and options as well as description of the trained model object.

```
set.seed(11, kind = "L'Ecuyer-CMRG")

idx.train <- rownames(labels)[train_test_split]
idx.test <- setdiff(rownames(labels), idx.train)

training_data <- sample_data[idx.train, ]
datatypes <- list(exp = c("exp"))
training_labels <- labels[idx.train, 1]
feature_sets <- pathways
global_features_names <- NULL

rf_params <- list(ttype = "binary", bin.perf = "bacc", regression.q = 0.05, importance = "impurity",
  min.nfeat = 15, ntree = 2000, sample.frac = 0.5, replace = FALSE, weights = NULL,
  oob.cv = data.frame(min.node.prop = 0.01, mtry.prop = 0.25, ntree = 500))

aklimate_params <- list(topn = 5, subsetCV = TRUE, lamb = c(-15, 0), cvlen = 20,
  celnet = c(0.01, 0.002), type = "probability")

store_kernels <- FALSE
verbose <- TRUE

aklimate_model <- aklimate(training_data, datatypes, training_labels, feature_sets,
  global_features_names, rf_params, aklimate_params, store_kernels, verbose)
```

## Test the Trained AKLIMATE Model

The `predict()` function is used to apply the trained AKLIMATE model to test samples. In this example, the predicted labels are stored in the `aklimate_model.preds` variable.

```
aklimate_model.preds <- predict(aklimate_model, sample_data, pathways, NULL, FALSE)$preds
```

## Get Feature Set Importance from the Trained AKLIMATE Model

The `rank_features()` function is used to get the feature set importance scores.

```
ranked_features <- rank_features(akl_obj=aklimate_model)
```

## Get the Relative Importance of Feature Datatypes

The `rank_importance_type()` function outputs the relative importance of the specified feature datatypes. In this example, there are only expression features, so we expect to see that the `exp` datatype will get the full importance of `1`.

```
datatype_importance <- rank_importance_type(suffs=c("exp"), ranked_features)
```
