#chrisw 20200424
#build an image for running AKLIMATE

#FROM stuartlab/aklimate:dev_no_spicer
FROM stuartlab/aklimate:dev

COPY ./dockerfile_scripts /dockerfile_scripts

RUN ["bash", "/dockerfile_scripts/install_r_stuff_aklimate.sh"]
